### ISSUE TITLE
iris start in docker fails - serious design error  of  repo

### ISSUE THREAD

**Issue by r-cemper** [ericmariasis/iris-email-analyzer-app#1]
iris-1  | [INFO] ...started InterSystems IRIS instance IRIS
iris-1  | [INFO] Executing command /docker-entrypoint.sh iris-after-start ...
iris-1  | /docker-entrypoint.sh: line 68: /docker-entrypoint-initdb.d/entrypoint.sh: **Is a directory**
iris-1  | [INFO]
iris-1  | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/entrypoint.sh
iris-1  | [ERROR] Command "/docker-entrypoint.sh iris-after-start " exited with **status 32256**
iris-1  | [FATAL] Error executing post-startup command
iris-1  | [INFO] Shutting down InterSystems IRIS instance IRIS...
iris-1  | 07/26/24-18:14:23:161 (1023) 0 [Utility.Event] Shutting down InterSystems IRIS

**Comment by ericmariasis** [comment]
Hi would you be able to describe the steps you went through to try to run the app so I can potentially reproduce the problem?

**Comment by r-cemper** [comment]
- download git repo
- cd to new dir
- docker compose build
- docker compose up to see the issue
**entrypoint.sh** seems to be missing

**Comment by ericmariasis** [comment]
Oh OK I’ll see if I can get it working without the -d option. I anticipate that it’s a small issue, though the README does indicate to run it with -d.

Thank you for bringing this to my attention.

**Comment by r-cemper** [comment]
docker compuse up 
terminates with
iris-1  | [INFO] IRIS^/usr/irissys^2024.1.0.262.0com^down, last used Sat Jul 27 08:02:29 2024^iris.cpf^1972^52773^0^^IRIS^^^/usr/irissys^1972
iris-1  | [INFO] ...verified that InterSystems IRIS instance IRIS is down
iris-1 **exited with code 0**

**BUT** This message from dockeR is **MISLEADING**
the container is running anyhow and IRIS did a restart

SORRY for the confuson

**Comment by r-cemper** [comment]
confused ba doxker

**Comment by r-cemper** [comment]
the problem disappears if I remove this volume mapping from _docker-compose.yaml_

**- ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh**

Since there is just no **entrypoint.sh** file in the repo

**Comment by ericmariasis** [comment]
Yes I commented out that line and the issue no longer happens. Good call out though!
